version: '3.8'

services:
  # FastAPI Application
  fastapi-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ai-companion-api
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+aiomysql://ai_companion:secure_password@mysql:3306/ai_companion_db
      - REDIS_URL=redis://host.docker.internal:6379/0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ai-companion-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MySQL 8.0 Database
  mysql:
    image: mysql:8.0
    container_name: ai-companion-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ai_companion_db
      MYSQL_USER: ai_companion
      MYSQL_PASSWORD: secure_password
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ai-companion-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "ai_companion", "-psecure_password"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

# Persistent volumes
volumes:
  mysql_data:
    driver: local

# Custom network
networks:
  ai-companion-network:
    driver: bridge